// <auto-generated />
using System;
using BarbershopCrm.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarbershopCrm.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260518184559_RemoveConsentLogIpUserAgent")]
    partial class RemoveConsentLogIpUserAgent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("BarbershopCrm.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BranchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CancelReason")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("(datetime('now'))");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LoyaltyDiscountPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMERIC")
                        .HasDefaultValue(0m);

                    b.Property<string>("LoyaltyDiscountReason")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("None");

                    b.Property<int>("MasterId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PriceSnapshot")
                        .HasColumnType("NUMERIC");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Online");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Created");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("(datetime('now'))");

                    b.HasKey("BookingId");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("IX_Bookings_Client");

                    b.HasIndex("ServiceId");

                    b.HasIndex("BranchId", "StartDateTime")
                        .HasDatabaseName("IX_Bookings_Branch_Start");

                    b.HasIndex("MasterId", "StartDateTime")
                        .IsUnique()
                        .HasDatabaseName("IX_Bookings_Master_Start")
                        .HasFilter("Status IN ('Created','Confirmed')");

                    b.ToTable("Bookings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Bookings_Duration", "DurationMinutes > 0");

                            t.HasCheckConstraint("CK_Bookings_LoyaltyDiscount", "LoyaltyDiscountPercent >= 0 AND LoyaltyDiscountPercent <= 100");

                            t.HasCheckConstraint("CK_Bookings_Price", "PriceSnapshot >= 0");

                            t.HasCheckConstraint("CK_Bookings_Source", "Source IN ('Online','Admin','Lead')");

                            t.HasCheckConstraint("CK_Bookings_Status", "Status IN ('Created','Confirmed','Cancelled','Completed','NoShow')");
                        });
                });

            modelBuilder.Entity("BarbershopCrm.Domain.Entities.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("ClosingTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("OpeningTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("BranchId");

                    b.ToTable("Branches", null, t =>
                        {
                            t.HasCheckConstraint("CK_Branches_Hours", "ClosingTime > OpeningTime");

                            t.HasCheckConstraint("CK_Branches_IsActive", "IsActive IN (0,1)");
                        });

                    b.HasData(
                        new
                        {
                            BranchId = 1,
                            Address = "Краснодар, ул. Красная, 32",
                            ClosingTime = new TimeOnly(22, 0, 0),
                            IsActive = true,
                            Name = "Тихий час — Центр",
                            OpeningTime = new TimeOnly(10, 0, 0),
                            Phone = "+7 (861) 200-10-10"
                        },
                        new
                        {
                            BranchId = 2,
                            Address = "Краснодар, ул. Тургенева, 138",
                            ClosingTime = new TimeOnly(21, 0, 0),
                            IsActive = true,
                            Name = "Тихий час — Фестивальный",
                            OpeningTime = new TimeOnly(9, 0, 0),
                            Phone = "+7 (861) 200-10-11"
                        });
                });

            modelBuilder.Entity("BarbershopCrm.Domain.Entities.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("(datetime('now'))");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.HasKey("ClientId");

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("BarbershopCrm.Domain.Entities.ConsentLogEntry", b =>
                {
                    b.Property<int>("ConsentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AcceptedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("(datetime('now'))");

                    b.Property<string>("ConsentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConsentId");

                    b.HasIndex("PersonaId");

                    b.ToTable("ConsentLog", null, t =>
                        {
                            t.HasCheckConstraint("CK_ConsentLog_Type", "ConsentType IN ('PersonalData','Marketing')");
                        });
                });

            modelBuilder.Entity("BarbershopCrm.Domain.Entities.Lead", b =>
                {
                    b.Property<int>("LeadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("(datetime('now'))");

                    b.Property<int?>("CreatedBookingId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PersonaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PreferredBranchId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProcessedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("New");

                    b.HasKey("LeadId");

                    b.HasIndex("CreatedBookingId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("PreferredBranchId");

                    b.HasIndex("ProcessedByUserId");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_Leads_Status_Created");

                    b.ToTable("Leads", null, t =>
                        {
                            t.HasCheckConstraint("CK_Leads_Status", "Status IN ('New','InProgress','Done','Rejected')");
                        });
                });

            modelBuilder.Entity("BarbershopCrm.Domain.Entities.Master", b =>
                {
                    b.Property<int>("MasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio")
                        .HasColumnType("TEXT");

                    b.Property<int>("BranchId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("PersonaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MasterId");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("IX_Masters_Branch");

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.ToTable("Masters", null, t =>
                        {
                            t.HasCheckConstraint("CK_Masters_IsActive", "IsActive IN (0,1)");
                        });
                });

            modelBuilder.Entity("BarbershopCrm.Domain.Entities.MasterService", b =>
                {
                    b.Property<int>("MasterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MasterId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("MasterService", (string)null);
                });

            modelBuilder.Entity("BarbershopCrm.Domain.Entities.Persona", b =>
                {
                    b.Property<int>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PersonaId");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("UX_Persona_Phone");

                    b.ToTable("Persona", null, t =>
                        {
                            t.HasCheckConstraint("CK_Persona_Gender", "Gender IS NULL OR Gender IN ('М','Ж')");
                        });
                });

            modelBuilder.Entity("BarbershopCrm.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Code = "Owner",
                            Name = "Владелец сети"
                        },
                        new
                        {
                            RoleId = 2,
                            Code = "Admin",
                            Name = "Администратор филиала"
                        },
                        new
                        {
                            RoleId = 3,
                            Code = "Master",
                            Name = "Мастер"
                        },
                        new
                        {
                            RoleId = 4,
                            Code = "Client",
                            Name = "Клиент"
                        });
                });

            modelBuilder.Entity("BarbershopCrm.Domain.Entities.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("NUMERIC");

                    b.HasKey("ServiceId");

                    b.ToTable("Services", null, t =>
                        {
                            t.HasCheckConstraint("CK_Services_Duration", "DurationMinutes > 0");

                            t.HasCheckConstraint("CK_Services_IsActive", "IsActive IN (0,1)");

                            t.HasCheckConstraint("CK_Services_Price", "Price >= 0");
                        });

                    b.HasData(
                        new
                        {
                            ServiceId = 1,
                            Description = "Классическая мужская стрижка ножницами и машинкой.",
                            DurationMinutes = 60,
                            IsActive = true,
                            Name = "Мужская стрижка",
                            Price = 1500m
                        },
                        new
                        {
                            ServiceId = 2,
                            Description = "Короткая стрижка одной длиной.",
                            DurationMinutes = 30,
                            IsActive = true,
                            Name = "Стрижка машинкой",
                            Price = 800m
                        },
                        new
                        {
                            ServiceId = 3,
                            Description = "Классическое бритьё с горячим полотенцем.",
                            DurationMinutes = 45,
                            IsActive = true,
                            Name = "Бритьё опасной бритвой",
                            Price = 1200m
                        },
                        new
                        {
                            ServiceId = 4,
                            Description = "Моделирование контура и подравнивание бороды.",
                            DurationMinutes = 30,
                            IsActive = true,
                            Name = "Стрижка бороды",
                            Price = 700m
                        },
                        new
                        {
                            ServiceId = 5,
                            Description = "Тонирование седины в бороде.",
                            DurationMinutes = 30,
                            IsActive = true,
                            Name = "Камуфляж бороды",
                            Price = 900m
                        });
                });

            modelBuilder.Entity("BarbershopCrm.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BranchId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("(datetime('now'))");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PasswordIterations")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(100000);

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("IX_Users_Branch");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_IsActive", "IsActive IN (0,1)");

                            t.HasCheckConstraint("CK_Users_IsEmailConfirmed", "IsEmailConfirmed IN (0,1)");
                        });
                });

            modelBuilder.Entity("BarbershopCrm.Domain.Entities.UserSession", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("(datetime('now'))");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserSessions_User");

                    b.ToTable("UserSessions", (string)null);
                });

            modelBuilder.Entity("BarbershopCrm.Domain.Entities.UserToken", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TokenId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId", "Purpose")
                        .HasDatabaseName("IX_UserTokens_User_Purpose");

                    b.ToTable("UserTokens", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserTokens_Purpose", "Purpose IN ('PasswordReset')");
                        });
                });

            modelBuilder.Entity("BarbershopCrm.Domain.Entities.Visit", b =>
                {
                    b.Property<int>("VisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookingId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("(datetime('now'))");

                    b.Property<string>("MasterNotes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("NUMERIC");

                    b.HasKey("VisitId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("Visits", null, t =>
                        {
                            t.HasCheckConstraint("CK_Visits_Total", "TotalAmount >= 0");
                        });
                });

            modelBuilder.Entity("BarbershopCrm.Domain.Entities.WorkSchedule", b =>
                {
                    b.Property<int>("WorkScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BranchId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("MasterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScheduleType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("TEXT");

                    b.HasKey("WorkScheduleId");

                    b.HasIndex("BranchId");

                    b.HasIndex("MasterId", "WorkDate")
                        .HasDatabaseName("IX_WorkSchedules_Master_Date");

                    b.HasIndex("MasterId", "WorkDate", "StartTime")
                        .IsUnique()
                        .HasDatabaseName("UQ_WorkSchedules_Slot");

                    b.ToTable("WorkSchedules", null, t =>
                        {
                            t.HasCheckConstraint("CK_WorkSchedules_Times", "EndTime > StartTime");

                            t.HasCheckConstraint("CK_WorkSchedules_Type", "ScheduleType IN ('Work','Lunch','DayOff','Vacation','SickLeave')");
                        });
                });

            modelBuilder.Entity("BarbershopCrm.Domain.Entities.Booking", b =>
                {
                    b.HasOne("BarbershopCrm.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarbershopCrm.Domain.Entities.Client", "Client")
                        .WithMany("Bookings")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarbershopCrm.Domain.Entities.Master", "Master")
                        .WithMany()
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarbershopCrm.Domain.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Client");

                    b.Navigation("Master");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("BarbershopCrm.Domain.Entities.Client", b =>
                {
                    b.HasOne("BarbershopCrm.Domain.Entities.Persona", "Persona")
                        .WithOne("Client")
                        .HasForeignKey("BarbershopCrm.Domain.Entities.Client", "PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("BarbershopCrm.Domain.Entities.ConsentLogEntry", b =>
                {
                    b.HasOne("BarbershopCrm.Domain.Entities.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("BarbershopCrm.Domain.Entities.Lead", b =>
                {
                    b.HasOne("BarbershopCrm.Domain.Entities.Booking", "CreatedBooking")
                        .WithMany()
                        .HasForeignKey("CreatedBookingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BarbershopCrm.Domain.Entities.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BarbershopCrm.Domain.Entities.Branch", "PreferredBranch")
                        .WithMany()
                        .HasForeignKey("PreferredBranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BarbershopCrm.Domain.Entities.User", "ProcessedBy")
                        .WithMany()
                        .HasForeignKey("ProcessedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBooking");

                    b.Navigation("Persona");

                    b.Navigation("PreferredBranch");

                    b.Navigation("ProcessedBy");
                });

            modelBuilder.Entity("BarbershopCrm.Domain.Entities.Master", b =>
                {
                    b.HasOne("BarbershopCrm.Domain.Entities.Branch", "Branch")
                        .WithMany("Masters")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarbershopCrm.Domain.Entities.Persona", "Persona")
                        .WithOne("Master")
                        .HasForeignKey("BarbershopCrm.Domain.Entities.Master", "PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("BarbershopCrm.Domain.Entities.MasterService", b =>
                {
                    b.HasOne("BarbershopCrm.Domain.Entities.Master", "Master")
                        .WithMany("MasterServices")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarbershopCrm.Domain.Entities.Service", "Service")
                        .WithMany("MasterServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Master");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("BarbershopCrm.Domain.Entities.User", b =>
                {
                    b.HasOne("BarbershopCrm.Domain.Entities.Branch", "Branch")
                        .WithMany("Admins")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BarbershopCrm.Domain.Entities.Persona", "Persona")
                        .WithOne("User")
                        .HasForeignKey("BarbershopCrm.Domain.Entities.User", "PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarbershopCrm.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Persona");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BarbershopCrm.Domain.Entities.UserSession", b =>
                {
                    b.HasOne("BarbershopCrm.Domain.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BarbershopCrm.Domain.Entities.UserToken", b =>
                {
                    b.HasOne("BarbershopCrm.Domain.Entities.User", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BarbershopCrm.Domain.Entities.Visit", b =>
                {
                    b.HasOne("BarbershopCrm.Domain.Entities.Booking", "Booking")
                        .WithOne("Visit")
                        .HasForeignKey("BarbershopCrm.Domain.Entities.Visit", "BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("BarbershopCrm.Domain.Entities.WorkSchedule", b =>
                {
                    b.HasOne("BarbershopCrm.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarbershopCrm.Domain.Entities.Master", "Master")
                        .WithMany("Schedules")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Master");
                });

            modelBuilder.Entity("BarbershopCrm.Domain.Entities.Booking", b =>
                {
                    b.Navigation("Visit");
                });

            modelBuilder.Entity("BarbershopCrm.Domain.Entities.Branch", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("Masters");
                });

            modelBuilder.Entity("BarbershopCrm.Domain.Entities.Client", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("BarbershopCrm.Domain.Entities.Master", b =>
                {
                    b.Navigation("MasterServices");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("BarbershopCrm.Domain.Entities.Persona", b =>
                {
                    b.Navigation("Client");

                    b.Navigation("Master");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BarbershopCrm.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BarbershopCrm.Domain.Entities.Service", b =>
                {
                    b.Navigation("MasterServices");
                });

            modelBuilder.Entity("BarbershopCrm.Domain.Entities.User", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
